#!/usr/bin/env python

from flask import Flask
from flask import render_template
from flask import send_from_directory

import os

# lmaooo
os.rename('elongated_musk', 'elongated_musk.html')

app = Flask(__name__)

@app.route("/")
def meme_page():
    print("going")
    root_dir = os.path.dirname(os.getcwd())
    return send_from_directory(os.path.join(root_dir), 'elongated_musk.html')

if __name__ == '__main__':
    app.run(host="0.0.0.0", port=80)